name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pob_itbuu@hotmail.co.th
          password: Docker@1234

      - name: Build Docker image
        run: docker build -t pos:latest .
      - name: Run Docker container
        run: docker run -d -p 8087:8087 --name pos pos:latest
